// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPBtMCcWqkSQ56hKB2Xuz9YBep1HgftyU',
    appId: '1:610243973978:web:72d315e8fe1666edbd1963',
    messagingSenderId: '610243973978',
    projectId: 'flash-chat-c28a0',
    authDomain: 'flash-chat-c28a0.firebaseapp.com',
    storageBucket: 'flash-chat-c28a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm8sVpQTYEyBZHFZ-CrI-UqWyKmi5pvq4',
    appId: '1:610243973978:android:b272a6bfdc36e214bd1963',
    messagingSenderId: '610243973978',
    projectId: 'flash-chat-c28a0',
    storageBucket: 'flash-chat-c28a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkWFIDbkKex7H4ZlLNYyh017Thj3RKuIQ',
    appId: '1:610243973978:ios:359d24060d8cf428bd1963',
    messagingSenderId: '610243973978',
    projectId: 'flash-chat-c28a0',
    storageBucket: 'flash-chat-c28a0.appspot.com',
    iosBundleId: 'com.example.flashChatStartingProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkWFIDbkKex7H4ZlLNYyh017Thj3RKuIQ',
    appId: '1:610243973978:ios:c2a7da04a99c4ae9bd1963',
    messagingSenderId: '610243973978',
    projectId: 'flash-chat-c28a0',
    storageBucket: 'flash-chat-c28a0.appspot.com',
    iosBundleId: 'com.example.flashChatStartingProject2.RunnerTests',
  );
}
